name: Coming Together
favicon: null
layout_spectrum: 0.5532446855213493
typography_spectrum: 0.08784374687820673
title: Beaver Fever
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7197253236081451
  lightness: 0.41897484892979264
  saturation: 0.057104366132989526
  rhythmicContrast: 0.5992236773017794
purpose: []
